add: a configurable HTTP transport connect timeout
honeycombio/honeycomb-lambda-extension pull request #111
Opened 2022-10-14 06:47 UTC by danvendia

## Which problem is this PR solving?
This is partially solving issue #101; it is providing a means to configure just the connect timeout. I think this is the most important of the timeout settings, so I'm limiting scope in this PR to just that.

## Short description of the changes
* A new env variable HONEYCOMB_CONNECT_TIMEOUT can be used to customize the HTTP transport connection timeout for the underlying libhoney-go client so that when there are netowrk connectivity issues, batch upload will fail faster and not hang for the full duration of the batch upload timeout. The default connection timeout is set to 3 seconds if not specified. This closes out a portion of issue #101, as it's only handling connect timeout for now. Limiting network connection timeouts is critical for a Lambda extension as it's possible for an extension to extend the duration of a function invocation and result in function timeouts. This has real world impacts beyond just costs. This scenario can easily result in overall Lambda account concurrency limits being exceeded, which will prevent further function executions from running (essentially a denial of service). Furthermore, when function timeouts occur, this causes the underyling Lambda sandbox to terminate resulting in performance impact in the form of cold starts for all invocations.
* Refactor: move libhoney-go code out of main package and into an eventpublisher package which is just a wrapper around the libhoney client with reduced API surface that is configured with default network settings more appropriate for a Lambda extension. This move to a separate package also helps with the unit tests as this can be written outside of package main.

2022-10-18 10:51 UTC, MikeGoldsmith commented
Hi @danvendia - thanks for putting this PR together. I should have time to review over the next or so.

2022-10-18 13:39 UTC, MikeGoldsmith requested changes
This looks really good, thanks @danvendia 👍🏻 

I've left some feedback on not updating the user agent and a query about what the default timeout should be.

2022-10-18 14:33 UTC, robbkidd commented on main.go
> +		UserAgent:        fmt.Sprintf("honeycomb-lambda-extension-%s/%s", runtime.GOARCH, version),
This was probably the result of @danvendia's work on this feature from before #98 merged (and released in v10.4.0) in which the user-agent changed  to conform to [the standard format](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent). Prior to that PR, the user-agent looked like Dan has it here. 

We'll want to keep `fmt.Sprintf("honeycomb-lambda-extension/%s (%s)", version, runtime.GOARCH)` as is in Mike's suggested change.

2022-10-18 14:49 UTC, danvendia commented on main.go
> +		UserAgent:        fmt.Sprintf("honeycomb-lambda-extension-%s/%s", runtime.GOARCH, version),
Good catch! Definitely unintentional

2022-10-18 17:21 UTC, danvendia commented on README.md
> +  Default: 3s (3 seconds).
I did a quick test using artillery to do an HTTP get (every second for 10 seconds) on https://api.honeycomb.io/ with 10 concurrent executions and ran that in each AWS region. Mostly just interested in the max response time as that is likely to happen on initial connection and then after that the connection will be re-used. The response time measured here is time to first byte (TTFB), which is measuring way more than we need to here as we are only concerned with the time to establish the underlying TCP connection, but if TTFB is within limits we can be confident our connect timeout is fine. Based on results below I'd say we could probably drop connection timeout further, but I'm fine with 3 seconds.

Honeycomb metrics showing response time of artillery runs with regions in this order: `"eu-north-1" "ap-south-1" "eu-west-3" "eu-west-2" "eu-west-1" "ap-northeast-3" "ap-northeast-2" "ap-northeast-1" "sa-east-1" "ca-central-1" "ap-southeast-1" "ap-southeast-2" "eu-central-1" "us-east-1" "us-east-2" "us-west-1" "us-west-2"`
<img width="1775" alt="Screen Shot 2022-10-18 at 10 17 20 AM" src="https://user-images.githubusercontent.com/84951447/196500451-7002e8d7-c87f-4f19-b081-e0b4a79ddc40.png">

2022-10-21 20:29 UTC, robbkidd approved these changes
![You get a timeout!](https://user-images.githubusercontent.com/517302/197283198-06940240-c542-43f1-b757-bbb139864973.gif)

Nice, @danvendia, and thank you for the submission! It has inspired me to follow-up with some more refactoring.

2022-10-21 20:29 UTC, merged