Remove unnecessary panic when unable to subscribe to logs
honeycombio/honeycomb-lambda-extension pull request #5
Opened 2020-11-20 20:34 UTC by paulosman

The extension shouldn't panic when unable to make a successful subscription request to the logs API - just output a warning log message. Also, adding a user agent string with a version.

2020-11-20 21:13 UTC, MikeGoldsmith requested changes
Looks good - just one suggestion regarding version title in changelog

2020-11-20 21:13 UTC, MikeGoldsmith commented on CHANGELOG.md
> +## Version 3 (2020-11-20)
Use same version in `version` file.

```suggestion
## Version 0.3.0 (2020-11-20)
```

2020-11-20 21:15 UTC, paulosman commented
> Looks good - just one suggestion regarding version title in changelog

Hmm. This raises a good question actually. The way this is published, it's deployed with [publish-layer-version](https://docs.aws.amazon.com/cli/latest/reference/lambda/publish-layer-version.html) which returns a single version number. I'll keep the CHANGELOG as is but update `version.go`.

2020-11-21 05:12 UTC, MikeGoldsmith approved these changes

2020-11-21 14:45 UTC, merged